export const supportedRegions = {
  DZ: { name: "Algeria", langs: ["ar", "fr"] },
  MA: { name: "Morocco", langs: ["ar", "fr"] },
  TN: { name: "Tunisia", langs: ["ar", "fr"] },
  EG: { name: "Egypt", langs: ["ar"] },
  SA: { name: "Saudi Arabia", langs: ["ar"] },
  AE: { name: "United Arab Emirates", langs: ["ar"] },
  QA: { name: "Qatar", langs: ["ar"] },
  KW: { name: "Kuwait", langs: ["ar"] },
  LB: { name: "Lebanon", langs: ["ar", "fr"] },
  LY: { name: "Libya", langs: ["ar"] },
  SY: { name: "Syria", langs: ["ar"] },
  IQ: { name: "Iraq", langs: ["ar"] },
  JO: { name: "Jordan", langs: ["ar"] },
  OM: { name: "Oman", langs: ["ar"] },
  BH: { name: "Bahrain", langs: ["ar"] },
  YE: { name: "Yemen", langs: ["ar"] },
  SD: { name: "Sudan", langs: ["ar"] },
  FR: { name: "France", langs: ["fr"] },
  BE: { name: "Belgium", langs: ["fr", "nl"] },
  CH: { name: "Switzerland", langs: ["fr", "de"] },
  CA: { name: "Canada", langs: ["fr", "en"] },
  US: { name: "USA", langs: ["en"] },
  GB: { name: "United Kingdom", langs: ["en"] },
  DE: { name: "Germany", langs: ["de", "en"] },
  ES: { name: "Spain", langs: ["es", "en"] },
  IT: { name: "Italy", langs: ["it"] },
  PT: { name: "Portugal", langs: ["pt"] },
  BR: { name: "Brazil", langs: ["pt"] },
  TR: { name: "Turkey", langs: ["tr", "en"] },
  RU: { name: "Russia", langs: ["ru"] },
  BY: { name: "Belarus", langs: ["ru"] },
  UA: { name: "Ukraine", langs: ["uk"] },
  PL: { name: "Poland", langs: ["pl"] },
  RO: { name: "Romania", langs: ["ro"] },
  GR: { name: "Greece", langs: ["el"] },
  HU: { name: "Hungary", langs: ["hu"] },
  CZ: { name: "Czech Republic", langs: ["cs"] },
  DK: { name: "Denmark", langs: ["da"] },
  NO: { name: "Norway", langs: ["no"] },
  SE: { name: "Sweden", langs: ["sv"] },
  FI: { name: "Finland", langs: ["fi"] },
  NL: { name: "Netherlands", langs: ["nl"] },
  IE: { name: "Ireland", langs: ["en"] },
  AT: { name: "Austria", langs: ["de"] },
  MX: { name: "Mexico", langs: ["es"] },
  AR: { name: "Argentina", langs: ["es"] },
  CO: { name: "Colombia", langs: ["es"] },
  CL: { name: "Chile", langs: ["es"] },
  PE: { name: "Peru", langs: ["es"] },
  SN: { name: "Senegal", langs: ["fr"] },
  AO: { name: "Angola", langs: ["pt"] },
  ZA: { name: "South Africa", langs: ["en"] },
  CN: { name: "China", langs: ["zh"] },
  SG: { name: "Singapore", langs: ["zh", "en"] },
  TW: { name: "Taiwan", langs: ["zh"] },
  JP: { name: "Japan", langs: ["ja"] },
  KR: { name: "South Korea", langs: ["ko"] },
  IN: { name: "India", langs: ["hi", "en"] },
  AU: { name: "Australia", langs: ["en"] },
  NZ: { name: "New Zealand", langs: ["en"] },
  TH: { name: "Thailand", langs: ["th"] },
  VN: { name: "Vietnam", langs: ["vi"] },
  ID: { name: "Indonesia", langs: ["id"] },
  MY: { name: "Malaysia", langs: ["ms"] },
};

export type RegionCode = keyof typeof supportedRegions;

export const sortedRegions = Object.entries(supportedRegions).sort((a, b) =>
  a[1].name.localeCompare(b[1].name)
);
