/** Register form dictionaries for Singapore multilingual locales (zh, ms, ta). */

const baseFields = {
  vosAcces: "",
  lAlliance: "",
  sonProfil: "",
  stepText: "Screen {step} of 3",
  chooseRole: "",
  parentTab: "",
  schoolTab: "",
  ngoTab: "",
  instantGoogle: "",
  orEmail: "",
  fullNameParent: "",
  fullNameSchool: "",
  fullNameNgo: "",
  fullNamePlaceholderParent: "",
  fullNamePlaceholderSchool: "",
  fullNamePlaceholderNgo: "",
  username: "",
  usernamePlaceholder: "",
  email: "",
  emailPlaceholder: "",
  phone: "",
  phonePlaceholder: "",
  password: "",
  passwordPlaceholder: "••••••••",
  confirmPassword: "",
  confirmPasswordPlaceholder: "••••••••",
  matchPerfect: "",
  matchError: "",
  eightChars: "",
  uppercase: "",
  number: "",
  specialChar: "",
  next: "",
  previous: "",
  titleParentStep1: "",
  titleParentStep1Orange: "",
  titleSchoolStep1: "",
  titleSchoolStep1Orange: "",
  titleNgoStep1: "",
  titleNgoStep1Orange: "",
  subStep1Parent: "",
  subStep1School: "",
  subStep1Ngo: "",
  leftTitle1: "",
  leftTitle1Orange: "",
  leftSub1: "",
  leftTitle2: "",
  leftTitle2Orange: "",
  leftSub2: "",
  leftTitle3: "",
  leftTitle3Orange: "",
  leftSub3: "",
  allyTitle: "",
  allyDesc: "",
  allyNamePlaceholder: "",
  allyEmailPlaceholder: "",
  schoolIdentityTitle: "",
  schoolIdentityDesc: "",
  privateSchool: "",
  publicSchool: "",
  schoolAddressPlaceholder: "",
  schoolManagerPlaceholder: "",
  ngoTitle: "",
  ngoDesc: "",
  ngoDomainPlaceholder: "",
  ngoDomainEducation: "",
  ngoDomainSocial: "",
  ngoDomainCulture: "",
  ngoDomainHumanitarian: "",
  ngoAddressPlaceholder: "",
  ngoManagerPlaceholder: "",
  childFirstName: "",
  childFirstNamePlaceholder: "",
  childAge: "",
  childAgePlaceholder: "",
  childLevel: "",
  childSchool: "",
  childSchoolPlaceholder: "",
  securityCheck: "",
  securityCheckDesc: "",
  securityCodePlaceholder: "",
  finalizeButton: "",
  registerSchoolButton: "",
  registerNgoButton: "",
  termsText: "",
  alreadyHaveAccount: "",
  loginLink: "",
  digitalPresence: "",
  digitalPresencePlaceholderSchool: "",
  schoolDimension: "",
  classesCountPlaceholder: "",
  instCheck: "",
  instCheckDesc: "",
  digitalPresencePlaceholderNgo: "",
  beneficiariesCount: "",
  beneficiariesPlaceholder: "",
  orgCheck: "",
  orgCheckDesc: "",
  errNameEmpty: "",
  errUsernameEmpty: "",
  errUsernameTaken: "",
  errEmailEmpty: "",
  errPasswordEmpty: "",
  errPasswordsDoNotMatch: "",
  errCaptchaIncorrect: "",
  welcomeTitle: "",
};

export const registerDictZh = {
  ...baseFields,
  vosAcces: "登录信息",
  lAlliance: "教育伙伴",
  sonProfil: "孩子资料",
  stepText: "第 {step} 步，共 3 步",
  chooseRole: "选择您的角色",
  parentTab: "家长",
  schoolTab: "学校",
  ngoTab: "组织",
  instantGoogle: "使用 Google 快速登录",
  orEmail: "或通过邮箱手动注册",
  fullNameParent: "全名",
  fullNameSchool: "学校名称",
  fullNameNgo: "组织名称",
  fullNamePlaceholderParent: "例如：李明",
  fullNamePlaceholderSchool: "例如：莱佛士小学",
  fullNamePlaceholderNgo: "例如：新加坡红十字会",
  username: "用户名",
  usernamePlaceholder: "liming_sg",
  email: "电子邮箱",
  emailPlaceholder: "liming@example.com",
  phone: "电话",
  phonePlaceholder: "9123 4567",
  password: "密码",
  confirmPassword: "确认密码",
  matchPerfect: "完全匹配",
  matchError: "两次密码不一致",
  eightChars: "8 个字符",
  uppercase: "大写字母",
  number: "数字",
  specialChar: "特殊字符",
  next: "下一步",
  previous: "上一步",
  titleParentStep1: "唤醒",
  titleParentStep1Orange: "精英",
  titleSchoolStep1: "唤醒",
  titleSchoolStep1Orange: "精英",
  titleNgoStep1: "唤醒",
  titleNgoStep1Orange: "精英",
  subStep1Parent: "成为孩子非凡命运的建筑师。",
  subStep1School: "面向未来精英的卓越教育合作伙伴。",
  subStep1Ngo: "携手为孩子们创造更美好的明天。",
  leftTitle1: "唤醒",
  leftTitle1Orange: "精英",
  leftSub1: "成为孩子非凡命运的建筑师。",
  leftTitle2: "和谐",
  leftTitle2Orange: "伙伴",
  leftSub2: "携手同行，共同启航。",
  leftTitle3: "崛起",
  leftTitle3Orange: "天才",
  leftSub3: "照亮他们通往卓越的道路。",
  allyTitle: "您的教育伙伴",
  allyDesc: "教育是团队运动。邀请支持您的人（配偶、长辈等）共同协调努力。",
  allyNamePlaceholder: "例如：小美或伟明",
  allyEmailPlaceholder: "伙伴邮箱（可选）",
  schoolIdentityTitle: "学校信息",
  schoolIdentityDesc: "填写小学官方信息以确认我们的教育合作伙伴关系。",
  privateSchool: "私立学校",
  publicSchool: "公立学校",
  schoolAddressPlaceholder: "总部完整地址",
  schoolManagerPlaceholder: "负责人 / 校长姓名",
  ngoTitle: "社会承诺",
  ngoDesc: "明确您的人道主义使命范围，实现完美协同。",
  ngoDomainPlaceholder: "行动领域",
  ngoDomainEducation: "教育与支持",
  ngoDomainSocial: "社会融入",
  ngoDomainCulture: "文化与意识",
  ngoDomainHumanitarian: "综合人道主义",
  ngoAddressPlaceholder: "总部地址",
  ngoManagerPlaceholder: "组织负责人",
  childFirstName: "孩子名字",
  childFirstNamePlaceholder: "例如：欣怡或浩然",
  childAge: "年龄",
  childAgePlaceholder: "例如：8",
  childLevel: "年级",
  childSchool: "学校 / 机构",
  childSchoolPlaceholder: "搜索学校...",
  securityCheck: "安全验证",
  securityCheckDesc: "反机器人保护系统",
  securityCodePlaceholder: "输入验证码",
  finalizeButton: "完成注册",
  registerSchoolButton: "注册学校",
  registerNgoButton: "注册组织",
  termsText: "继续即表示您同意我们的条款和隐私政策。",
  alreadyHaveAccount: "已有账号？",
  loginLink: "登录",
  digitalPresence: "线上展示",
  digitalPresencePlaceholderSchool: "网站或 Facebook（例如 fb.com/school...）",
  schoolDimension: "学校规模",
  classesCountPlaceholder: "小学班级数量",
  instCheck: "机构验证",
  instCheckDesc: "机构安全系统",
  digitalPresencePlaceholderNgo: "网站或社交主页",
  beneficiariesCount: "受益人数",
  beneficiariesPlaceholder: "受助儿童估计人数",
  orgCheck: "组织验证",
  orgCheckDesc: "人道主义保护已启用",
  errNameEmpty: "请输入您的全名",
  errUsernameEmpty: "请选择用户名",
  errUsernameTaken: "用户名已被占用",
  errEmailEmpty: "请输入电子邮箱",
  errPasswordEmpty: "请输入密码",
  errPasswordsDoNotMatch: "两次密码不一致",
  errCaptchaIncorrect: "验证码不正确",
  welcomeTitle: "欢迎加入精英！",
};

export const registerDictEs = {
  ...baseFields,
  vosAcces: "Datos de acceso",
  lAlliance: "Alianza educativa",
  sonProfil: "Perfil del niño",
  stepText: "Pantalla {step} de 3",
  chooseRole: "Elige tu rol",
  parentTab: "Padres",
  schoolTab: "Escuela",
  ngoTab: "ONG",
  instantGoogle: "Acceso rápido con Google",
  orEmail: "O mediante correo electrónico",
  fullNameParent: "Nombre completo",
  fullNameSchool: "Nombre del centro",
  fullNameNgo: "Nombre de la organización",
  fullNamePlaceholderParent: "Ej.: Juan Pérez",
  fullNamePlaceholderSchool: "Ej.: Escuela Primaria N° 1",
  fullNamePlaceholderNgo: "Ej.: Cruz Roja Argentina",
  username: "Nombre de usuario",
  usernamePlaceholder: "juan_perez",
  email: "Correo electrónico",
  emailPlaceholder: "juan@email.com",
  phone: "Teléfono",
  phonePlaceholder: "11 2345 6789",
  password: "Contraseña",
  confirmPassword: "Confirmar contraseña",
  matchPerfect: "Coincidencia perfecta",
  matchError: "Las contraseñas no coinciden",
  eightChars: "8 caracteres",
  uppercase: "Mayúscula",
  number: "Número",
  specialChar: "Carácter especial",
  next: "Siguiente",
  previous: "Anterior",
  titleParentStep1: "Despertar de la",
  titleParentStep1Orange: "Excelencia",
  titleSchoolStep1: "Despertar de la",
  titleSchoolStep1Orange: "Excelencia",
  titleNgoStep1: "Despertar de la",
  titleNgoStep1Orange: "Excelencia",
  subStep1Parent: "Conviértete en arquitecto del futuro excepcional de tu hijo.",
  subStep1School: "Un socio educativo de excelencia para la élite del mañana.",
  subStep1Ngo: "Juntos construimos un mejor futuro para nuestros niños.",
  leftTitle1: "Despertar de la",
  leftTitle1Orange: "Excelencia",
  leftSub1: "Conviértete en arquitecto del futuro excepcional de tu hijo.",
  leftTitle2: "Armonía de",
  leftTitle2Orange: "Aliados",
  leftSub2: "Sincronicen sus esfuerzos para un arranque común.",
  leftTitle3: "Ascenso del",
  leftTitle3Orange: "Genio",
  leftSub3: "Ilumina su camino hacia la excelencia.",
  allyTitle: "Tu aliado educativo",
  allyDesc: "La educación es un trabajo en equipo. Invita a quien te apoya para coordinar esfuerzos.",
  allyNamePlaceholder: "Ej.: María o Luis",
  allyEmailPlaceholder: "Correo del aliado (opcional)",
  schoolIdentityTitle: "Identidad de la institución",
  schoolIdentityDesc: "Completa la información oficial de tu escuela primaria.",
  privateSchool: "Escuela privada",
  publicSchool: "Escuela pública",
  schoolAddressPlaceholder: "Dirección completa de la institución",
  schoolManagerPlaceholder: "Nombre del director/a responsable",
  ngoTitle: "Compromiso solidario",
  ngoDesc: "Define el área de acción humanitaria para una mejor sinergia.",
  ngoDomainPlaceholder: "Área de actividad",
  ngoDomainEducation: "Educación y apoyo",
  ngoDomainSocial: "Integración social",
  ngoDomainCulture: "Cultura y sensibilización",
  ngoDomainHumanitarian: "Acción humanitaria integral",
  ngoAddressPlaceholder: "Dirección de sede",
  ngoManagerPlaceholder: "Responsable de la organización",
  childFirstName: "Nombre del niño",
  childFirstNamePlaceholder: "Ej.: Sofía o Mateo",
  childAge: "Edad",
  childAgePlaceholder: "Ej.: 8",
  childLevel: "Nivel",
  childSchool: "Escuela / Institución",
  childSchoolPlaceholder: "Buscar escuela...",
  securityCheck: "Verificación de seguridad",
  securityCheckDesc: "Sistema de protección anti-bots",
  securityCodePlaceholder: "Introduce el código",
  finalizeButton: "Finalizar registro",
  registerSchoolButton: "Registrar institución",
  registerNgoButton: "Registrar organización",
  termsText: "Al continuar, aceptas nuestros términos y política de privacidad.",
  alreadyHaveAccount: "¿Ya tienes una cuenta?",
  loginLink: "Iniciar sesión",
  digitalPresence: "Presencia digital",
  digitalPresencePlaceholderSchool: "Sitio web o Facebook (ej.: fb.com/escuela...)",
  schoolDimension: "Tamaño de la institución",
  classesCountPlaceholder: "Cantidad de clases de primaria",
  instCheck: "Verificación institucional",
  instCheckDesc: "Sistema de seguridad institucional",
  digitalPresencePlaceholderNgo: "Sitio web o perfil social",
  beneficiariesCount: "Número de beneficiarios",
  beneficiariesPlaceholder: "Cantidad estimada de niños beneficiados",
  orgCheck: "Verificación de organización",
  orgCheckDesc: "Protección humanitaria activada",
  errNameEmpty: "Introduce tu nombre completo",
  errUsernameEmpty: "Elige un nombre de usuario",
  errUsernameTaken: "Ese nombre de usuario ya está en uso",
  errEmailEmpty: "Introduce tu correo electrónico",
  errPasswordEmpty: "Introduce una contraseña",
  errPasswordsDoNotMatch: "Las contraseñas no coinciden",
  errCaptchaIncorrect: "Código de seguridad incorrecto",
  welcomeTitle: "¡Bienvenido a la Elite!",
};

export const registerDictMs = {
  ...baseFields,
  vosAcces: "Maklumat Log Masuk",
  lAlliance: "Rakan Pendidikan",
  sonProfil: "Profil Anak",
  stepText: "Skrin {step} daripada 3",
  chooseRole: "Pilih peranan anda",
  parentTab: "Ibu Bapa",
  schoolTab: "Sekolah",
  ngoTab: "NGO",
  instantGoogle: "Log masuk pantas dengan Google",
  orEmail: "Atau melalui e-mel manual",
  fullNameParent: "Nama Penuh",
  fullNameSchool: "Nama Sekolah",
  fullNameNgo: "Nama Organisasi",
  fullNamePlaceholderParent: "cth. Ahmad bin Ali",
  fullNamePlaceholderSchool: "cth. Sekolah Rendah Sunrise",
  fullNamePlaceholderNgo: "cth. Palang Merah Singapura",
  username: "Nama Pengguna",
  usernamePlaceholder: "ahmad_sg",
  email: "E-mel",
  emailPlaceholder: "ahmad@example.com",
  phone: "Telefon",
  phonePlaceholder: "9123 4567",
  password: "Kata Laluan",
  confirmPassword: "Sahkan Kata Laluan",
  matchPerfect: "Padanan sempurna",
  matchError: "Kata laluan tidak sepadan",
  eightChars: "8 aksara",
  uppercase: "Huruf besar",
  number: "Nombor",
  specialChar: "Aksara khas",
  next: "Seterusnya",
  previous: "Kembali",
  titleParentStep1: "Kebangkitan",
  titleParentStep1Orange: "Elit",
  titleSchoolStep1: "Kebangkitan",
  titleSchoolStep1Orange: "Elit",
  titleNgoStep1: "Kebangkitan",
  titleNgoStep1Orange: "Elit",
  subStep1Parent: "Jadilah arkitek destinasi luar biasa anak anda.",
  subStep1School: "Rakan pendidikan terkemuka untuk elit masa depan.",
  subStep1Ngo: "Bersama-sama membina masa depan yang lebih baik untuk kanak-kanak.",
  leftTitle1: "Kebangkitan",
  leftTitle1Orange: "Elit",
  leftSub1: "Jadilah arkitek destinasi luar biasa anak anda.",
  leftTitle2: "Harmoni",
  leftTitle2Orange: "Rakan",
  leftSub2: "Selaraskan usaha untuk kejayaan bersama.",
  leftTitle3: "Kebangkitan",
  leftTitle3Orange: "Genius",
  leftSub3: "Terangi jalan mereka menuju kecemerlangan.",
  allyTitle: "Rakan Pendidikan Anda",
  allyDesc: "Pendidikan adalah sukan berpasukan. Jemput orang yang menyokong anda untuk menyelaraskan usaha.",
  allyNamePlaceholder: "cth. Siti atau Ali",
  allyEmailPlaceholder: "E-mel rakan (Pilihan)",
  schoolIdentityTitle: "Identiti Sekolah",
  schoolIdentityDesc: "Lengkapkan maklumat rasmi sekolah rendah untuk mengesahkan perkongsian pendidikan.",
  privateSchool: "Sekolah Swasta",
  publicSchool: "Sekolah Awam",
  schoolAddressPlaceholder: "Alamat penuh ibu pejabat",
  schoolManagerPlaceholder: "Nama pengurus / pengetua",
  ngoTitle: "Komitmen Sosial",
  ngoDesc: "Tentukan skop misi kemanusiaan anda untuk sinergi yang sempurna.",
  ngoDomainPlaceholder: "Bidang tindakan",
  ngoDomainEducation: "Pendidikan & Sokongan",
  ngoDomainSocial: "Penyertaan sosial",
  ngoDomainCulture: "Budaya & Kesedaran",
  ngoDomainHumanitarian: "Kemanusiaan menyeluruh",
  ngoAddressPlaceholder: "Alamat ibu pejabat",
  ngoManagerPlaceholder: "Pengurus organisasi",
  childFirstName: "Nama pertama anak",
  childFirstNamePlaceholder: "cth. Aisyah atau Adam",
  childAge: "Umur",
  childAgePlaceholder: "cth. 8",
  childLevel: "Tahap / Darjah",
  childSchool: "Sekolah / Institusi",
  childSchoolPlaceholder: "Cari sekolah...",
  securityCheck: "Pengesahan Keselamatan",
  securityCheckDesc: "Sistem anti-robot dilindungi",
  securityCodePlaceholder: "Masukkan kod",
  finalizeButton: "Selesaikan Pendaftaran",
  registerSchoolButton: "Daftar Sekolah",
  registerNgoButton: "Daftar Organisasi",
  termsText: "Dengan meneruskan, anda bersetuju dengan terma dan dasar privasi kami.",
  alreadyHaveAccount: "Sudah mempunyai akaun?",
  loginLink: "Log Masuk",
  digitalPresence: "Kehadiran Digital",
  digitalPresencePlaceholderSchool: "Laman web atau Facebook (cth. fb.com/sekolah...)",
  schoolDimension: "Saiz Sekolah",
  classesCountPlaceholder: "Bilangan kelas rendah",
  instCheck: "Pengesahan Institusi",
  instCheckDesc: "Sistem institusi dilindungi",
  digitalPresencePlaceholderNgo: "Laman web atau profil sosial",
  beneficiariesCount: "Bilangan Penerima Manfaat",
  beneficiariesPlaceholder: "Anggaran bilangan kanak-kanak",
  orgCheck: "Pengesahan Organisasi",
  orgCheckDesc: "Perlindungan kemanusiaan aktif",
  errNameEmpty: "Sila masukkan nama penuh anda",
  errUsernameEmpty: "Sila pilih nama pengguna",
  errUsernameTaken: "Nama pengguna sudah digunakan",
  errEmailEmpty: "Sila masukkan e-mel anda",
  errPasswordEmpty: "Sila masukkan kata laluan",
  errPasswordsDoNotMatch: "Kata laluan tidak sepadan",
  errCaptchaIncorrect: "Kod keselamatan tidak betul",
  welcomeTitle: "Selamat datang ke Elit!",
};

export const registerDictTa = {
  ...baseFields,
  vosAcces: "உள்நுழைவு விவரங்கள்",
  lAlliance: "கல்வி கூட்டாளி",
  sonProfil: "குழந்தை விவரம்",
  stepText: "திரை {step} / 3",
  chooseRole: "உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்",
  parentTab: "பெற்றோர்",
  schoolTab: "பள்ளி",
  ngoTab: "அமைப்பு",
  instantGoogle: "Google மூலம் விரைவாக உள்நுழைக",
  orEmail: "அல்லது மின்னஞ்சல் மூலம்",
  fullNameParent: "முழு பெயர்",
  fullNameSchool: "பள்ளி பெயர்",
  fullNameNgo: "அமைப்பு பெயர்",
  fullNamePlaceholderParent: "எ.கா. ராஜ் குமார்",
  fullNamePlaceholderSchool: "எ.கா. சன்ரைஸ் தொடக்கப்பள்ளி",
  fullNamePlaceholderNgo: "எ.கா. சிங்கப்பூர் சிவப்பு சிலுவை",
  username: "பயனர் பெயர்",
  usernamePlaceholder: "raj_kumar",
  email: "மின்னஞ்சல்",
  emailPlaceholder: "raj@example.com",
  phone: "தொலைபேசி",
  phonePlaceholder: "9123 4567",
  password: "கடவுச்சொல்",
  confirmPassword: "கடவுச்சொலை உறுதிப்படுத்தவும்",
  matchPerfect: "சரியாக பொருந்துகிறது",
  matchError: "கடவுச்சொற்கள் பொருந்தவில்லை",
  eightChars: "8 எழுத்துகள்",
  uppercase: "பெரிய எழுத்து",
  number: "எண்",
  specialChar: "சிறப்பு எழுத்து",
  next: "அடுத்து",
  previous: "பின்செல்",
  titleParentStep1: "விழிப்புணர்வு",
  titleParentStep1Orange: "எலிட்",
  titleSchoolStep1: "விழிப்புணர்வு",
  titleSchoolStep1Orange: "எலிட்",
  titleNgoStep1: "விழிப்புணர்வு",
  titleNgoStep1Orange: "எலிட்",
  subStep1Parent: "உங்கள் குழந்தையின் அசாதாரண விதியின் கட்டட நிர்மாணியாக இருங்கள்.",
  subStep1School: "எதிர்கால எலிட்டிற்கான சிறந்த கல்வி கூட்டாளி.",
  subStep1Ngo: "குழந்தைகளுக்கான சிறந்த நாளை ஒன்றிணைந்து கட்டுவோம்.",
  leftTitle1: "விழிப்புணர்வு",
  leftTitle1Orange: "எலிட்",
  leftSub1: "உங்கள் குழந்தையின் அசாதாரண விதியின் கட்டட நிர்மாணியாக இருங்கள்.",
  leftTitle2: "இணக்கம்",
  leftTitle2Orange: "கூட்டாளிகள்",
  leftSub2: "பொதுவான வெற்றிக்காக ஒருங்கிணைந்து செயல்படுங்கள்.",
  leftTitle3: "உயர்வு",
  leftTitle3Orange: "மேதை",
  leftSub3: "சிறப்பை நோக்கிய அவர்களின் பாதையை ஒளிரச் செய்யுங்கள்.",
  allyTitle: "உங்கள் கல்வி கூட்டாளி",
  allyDesc: "கல்வி ஒரு குழு விளையாட்டு. உங்களை ஆதரிக்கும் நபரை அழைத்து முயற்சிகளை ஒருங்கிணைக்கவும்.",
  allyNamePlaceholder: "எ.கா. பிரியா அல்லது குமார்",
  allyEmailPlaceholder: "கூட்டாளி மின்னஞ்சல் (விருப்பம்)",
  schoolIdentityTitle: "பள்ளி அடையாளம்",
  schoolIdentityDesc: "எங்கள் கல்வி கூட்டாண்மையை உறுதிப்படுத்த அதிகாரப்பூர்வ தகவலை நிரப்பவும்.",
  privateSchool: "தனியார் பள்ளி",
  publicSchool: "அரசுப் பள்ளி",
  schoolAddressPlaceholder: "தலைமையக முழு முகவரி",
  schoolManagerPlaceholder: "மேலாளர் / தலைமை ஆசிரியர்",
  ngoTitle: "சமூக அர்ப்பணிப்பு",
  ngoDesc: "சரியான ஒத்துழைப்புக்காக உங்கள் மனிதாபிக் பணியின் வரம்பை வரையறுக்கவும்.",
  ngoDomainPlaceholder: "செயல்பாட்டுத் துறை",
  ngoDomainEducation: "கல்வி & ஆதரவு",
  ngoDomainSocial: "சமூக இணக்கம்",
  ngoDomainCulture: "கலாச்சாரம் & விழிப்புணர்வு",
  ngoDomainHumanitarian: "விரிவான மனிதாபிகம்",
  ngoAddressPlaceholder: "தலைமையக முகவரி",
  ngoManagerPlaceholder: "அமைப்பு பொறுப்பாளர்",
  childFirstName: "குழந்தையின் பெயர்",
  childFirstNamePlaceholder: "எ.கா. பிரியா அல்லது அருண்",
  childAge: "வயது",
  childAgePlaceholder: "எ.கா. 8",
  childLevel: "வகுப்பு",
  childSchool: "பள்ளி / நிறுவனம்",
  childSchoolPlaceholder: "பள்ளியைத் தேடுங்கள்...",
  securityCheck: "பாதுகாப்பு சரிபார்ப்பு",
  securityCheckDesc: "பாதுகாக்கப்பட்ட ரோபோ எதிர்ப்பு அமைப்பு",
  securityCodePlaceholder: "குறியீட்டை உள்ளிடவும்",
  finalizeButton: "பதிவை முடிக்கவும்",
  registerSchoolButton: "பள்ளியை பதிவு செய்யவும்",
  registerNgoButton: "அமைப்பை பதிவு செய்யவும்",
  termsText: "தொடர்வதன் மூலம் எங்கள் விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறீர்கள்.",
  alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
  loginLink: "உள்நுழை",
  digitalPresence: "டிஜிட்டல் இருப்பு",
  digitalPresencePlaceholderSchool: "வலைத்தளம் அல்லது Facebook (எ.கா. fb.com/school...)",
  schoolDimension: "பள்ளி அளவு",
  classesCountPlaceholder: "தொடக்கப்பள்ளி வகுப்புகளின் எண்ணிக்கை",
  instCheck: "நிறுவன சரிபார்ப்பு",
  instCheckDesc: "நிறுவன பாதுகாப்பு அமைப்பு",
  digitalPresencePlaceholderNgo: "வலைத்தளம் அல்லது சமூக வலைப்பக்கம்",
  beneficiariesCount: "பயனாளிகளின் எண்ணிக்கை",
  beneficiariesPlaceholder: "ஆதரிக்கப்படும் குழந்தைகளின் எண்ணிக்கை",
  orgCheck: "அமைப்பு சரிபார்ப்பு",
  orgCheckDesc: "மனிதாபிக பாதுகாப்பு செயலில்",
  errNameEmpty: "உங்கள் முழு பெயரை உள்ளிடவும்",
  errUsernameEmpty: "பயனர் பெயரைத் தேர்ந்தெடுக்கவும்",
  errUsernameTaken: "பயனர் பெயர் ஏற்கனவே பயன்பாட்டில் உள்ளது",
  errEmailEmpty: "மின்னஞ்சலை உள்ளிடவும்",
  errPasswordEmpty: "கடவுச்சொல்லை உள்ளிடவும்",
  errPasswordsDoNotMatch: "கடவுச்சொற்கள் பொருந்தவில்லை",
  errCaptchaIncorrect: "தவறான பாதுகாப்புக் குறியீடு",
  welcomeTitle: "எலிட்டில் வரவேற்கிறோம்!",
};

export const registerDictKo = {
  ...baseFields,
  vosAcces: "로그인 정보",
  lAlliance: "교육 파트너",
  sonProfil: "자녀 프로필",
  stepText: "3단계 중 {step}단계",
  chooseRole: "역할을 선택하세요",
  parentTab: "학부모",
  schoolTab: "학교",
  ngoTab: "조직",
  instantGoogle: "Google로 빠른 로그인",
  orEmail: "또는 이메일로 가입",
  fullNameParent: "이름 (전체)",
  fullNameSchool: "학교 이름",
  fullNameNgo: "조직 이름",
  fullNamePlaceholderParent: "예: 김민준",
  fullNamePlaceholderSchool: "예: 서울초등학교",
  fullNamePlaceholderNgo: "예: 대한적십자사",
  username: "사용자 이름",
  usernamePlaceholder: "minjun_kr",
  email: "이메일",
  emailPlaceholder: "minjun@example.com",
  phone: "전화번호",
  phonePlaceholder: "010-1234-5678",
  password: "비밀번호",
  confirmPassword: "비밀번호 확인",
  matchPerfect: "일치함",
  matchError: "비밀번호가 일치하지 않습니다",
  eightChars: "8자 이상",
  uppercase: "대문자",
  number: "숫자",
  specialChar: "특수문자",
  next: "다음",
  previous: "이전",
  titleParentStep1: "천재성의",
  titleParentStep1Orange: "깨어남",
  titleSchoolStep1: "천재성의",
  titleSchoolStep1Orange: "깨어남",
  titleNgoStep1: "천재성의",
  titleNgoStep1Orange: "깨어남",
  subStep1Parent: "자녀의 특별한 미래를 설계하세요.",
  subStep1School: "미래 엘리트를 위한 최고의 교육 파트너.",
  subStep1Ngo: "아이들을 위한 더 나은 내일을 함께 만듭니다.",
  leftTitle1: "천재성의",
  leftTitle1Orange: "깨어남",
  leftSub1: "자녀의 특별한 미래를 설계하세요.",
  leftTitle2: "파트너의",
  leftTitle2Orange: "조화",
  leftSub2: "공동의 성공을 위해 힘을 합치세요.",
  leftTitle3: "천재성의",
  leftTitle3Orange: "비상",
  leftSub3: "성공으로 가는 길을 밝혀주세요.",
  allyTitle: "교육 파트너",
  allyDesc: "교육은 팀워크입니다. 함께할 파트너(배우자, 가족 등)를 초대하세요.",
  allyNamePlaceholder: "예: 지훈 또는 서연",
  allyEmailPlaceholder: "파트너 이메일 (선택 사항)",
  schoolIdentityTitle: "학교 정보",
  schoolIdentityDesc: "교육 파트너십을 확인하기 위해 공식 정보를 입력하세요.",
  privateSchool: "사립 학교",
  publicSchool: "공립 학교",
  schoolAddressPlaceholder: "본부 전체 주소",
  schoolManagerPlaceholder: "담당자 / 교장 이름",
  ngoTitle: "사회적 약속",
  ngoDesc: "완벽한 시너지를 위해 활동 분야를 정의하세요.",
  ngoDomainPlaceholder: "활동 분야",
  ngoDomainEducation: "교육 및 지원",
  ngoDomainSocial: "사회 통합",
  ngoDomainCulture: "문화 및 인식",
  ngoDomainHumanitarian: "종합 구호 활동",
  ngoAddressPlaceholder: "본부 주소",
  ngoManagerPlaceholder: "조직 책임자",
  childFirstName: "자녀 이름",
  childFirstNamePlaceholder: "예: 민준 또는 서연",
  childAge: "나이",
  childAgePlaceholder: "예: 8",
  childLevel: "학년",
  childSchool: "학교 / 기관",
  childSchoolPlaceholder: "학교 검색...",
  securityCheck: "보안 확인",
  securityCheckDesc: "안전한 봇 방지 시스템",
  securityCodePlaceholder: "코드 입력",
  finalizeButton: "가입 완료",
  registerSchoolButton: "학교 등록",
  registerNgoButton: "조직 등록",
  termsText: "계속 진행하면 이용 약관 및 개인정보 처리방침에 동의하는 것입니다.",
  alreadyHaveAccount: "이미 계정이 있으신가요?",
  loginLink: "로그인",
  digitalPresence: "온라인 정보",
  digitalPresencePlaceholderSchool: "웹사이트 또는 Facebook (예: fb.com/school...)",
  schoolDimension: "학교 규모",
  classesCountPlaceholder: "초등학교 학급 수",
  instCheck: "기관 확인",
  instCheckDesc: "기관 보안 시스템",
  digitalPresencePlaceholderNgo: "웹사이트 또는 소셜 프로필",
  beneficiariesCount: "수혜자 수",
  beneficiariesPlaceholder: "지원 대상 어린이 예상 수",
  orgCheck: "조직 확인",
  orgCheckDesc: "인도주의 보호 활성화",
  errNameEmpty: "전체 이름을 입력해주세요",
  errUsernameEmpty: "사용자 이름을 선택해주세요",
  errUsernameTaken: "이미 사용 중인 사용자 이름입니다",
  errEmailEmpty: "이메일을 입력해주세요",
  errPasswordEmpty: "비밀번호를 입력해주세요",
  errPasswordsDoNotMatch: "비밀번호가 일치하지 않습니다",
  errCaptchaIncorrect: "보안 코드가 올바르지 않습니다",
  welcomeTitle: "엘리트에 오신 것을 환영합니다!",
};

export const registerDictJa = {
  ...baseFields,
  vosAcces: "ログイン情報",
  lAlliance: "教育パートナー",
  sonProfil: "お子様のプロフィール",
  stepText: "ステップ {step} / 3",
  chooseRole: "役割を選択",
  parentTab: "保護者",
  schoolTab: "学校",
  ngoTab: "団体",
  instantGoogle: "Googleでクイックログイン",
  orEmail: "またはメールで手動登録",
  fullNameParent: "氏名",
  fullNameSchool: "学校名",
  fullNameNgo: "団体名",
  fullNamePlaceholderParent: "例：山田 太郎",
  fullNamePlaceholderSchool: "例：東京小学校",
  fullNamePlaceholderNgo: "例：日本赤十字社",
  username: "ユーザー名",
  usernamePlaceholder: "taro_yamada",
  email: "メールアドレス",
  emailPlaceholder: "taro@example.jp",
  phone: "電話番号",
  phonePlaceholder: "090-1234-5678",
  password: "パスワード",
  confirmPassword: "パスワード確認",
  matchPerfect: "一致しました",
  matchError: "パスワードが一致しません",
  eightChars: "8文字以上",
  uppercase: "大文字",
  number: "数字",
  specialChar: "記号",
  next: "次へ",
  previous: "戻る",
  titleParentStep1: "才能の",
  titleParentStep1Orange: "覚醒",
  titleSchoolStep1: "才能の",
  titleSchoolStep1Orange: "覚醒",
  titleNgoStep1: "才能の",
  titleNgoStep1Orange: "覚醒",
  subStep1Parent: "お子様の特別な未来を設計する建築家になってください。",
  subStep1School: "未来のエリートのための卓越した教育パートナー。",
  subStep1Ngo: "子どもたちのより良い明日を共に築きましょう。",
  leftTitle1: "才能の",
  leftTitle1Orange: "覚醒",
  leftSub1: "お子様の特別な未来を設計する建築家になってください。",
  leftTitle2: "パートナーの",
  leftTitle2Orange: "調和",
  leftSub2: "共通の成功のために力を合わせましょう。",
  leftTitle3: "天才への",
  leftTitle3Orange: "昇華",
  leftSub3: "卓越への道を照らしましょう。",
  allyTitle: "教育パートナー",
  allyDesc: "教育はチームワークです。配偶者や家族など、伴走者を招待して努力を調整しましょう。",
  allyNamePlaceholder: "例：花子 または 太郎",
  allyEmailPlaceholder: "パートナーのメール（任意）",
  schoolIdentityTitle: "学校情報",
  schoolIdentityDesc: "教育パートナーシップ確認のため、小学校の公式情報をご入力ください。",
  privateSchool: "私立学校",
  publicSchool: "公立学校",
  schoolAddressPlaceholder: "本部の完全な住所",
  schoolManagerPlaceholder: "責任者 / 校長名",
  ngoTitle: "社会的コミットメント",
  ngoDesc: "理想的なシナジーのため、活動分野を定義してください。",
  ngoDomainPlaceholder: "活動分野",
  ngoDomainEducation: "教育と支援",
  ngoDomainSocial: "社会統合",
  ngoDomainCulture: "文化と意識",
  ngoDomainHumanitarian: "総合人道支援",
  ngoAddressPlaceholder: "本部住所",
  ngoManagerPlaceholder: "団体責任者",
  childFirstName: "お子様の名前",
  childFirstNamePlaceholder: "例：さくら または 蓮",
  childAge: "年齢",
  childAgePlaceholder: "例：8",
  childLevel: "学年",
  childSchool: "学校 / 機関",
  childSchoolPlaceholder: "学校を検索...",
  securityCheck: "セキュリティ確認",
  securityCheckDesc: "ボット対策システム",
  securityCodePlaceholder: "コードを入力",
  finalizeButton: "登録を完了",
  registerSchoolButton: "学校を登録",
  registerNgoButton: "団体を登録",
  termsText: "続行することで、利用規約およびプライバシーポリシーに同意したものとみなされます。",
  alreadyHaveAccount: "すでにアカウントをお持ちですか？",
  loginLink: "ログイン",
  digitalPresence: "オンライン情報",
  digitalPresencePlaceholderSchool: "ウェブサイトまたはFacebook（例：fb.com/school...）",
  schoolDimension: "学校規模",
  classesCountPlaceholder: "小学校の学級数",
  instCheck: "機関確認",
  instCheckDesc: "機関セキュリティシステム",
  digitalPresencePlaceholderNgo: "ウェブサイトまたはSNS",
  beneficiariesCount: "受益者数",
  beneficiariesPlaceholder: "支援対象児童の推定人数",
  orgCheck: "団体確認",
  orgCheckDesc: "人道保護が有効",
  errNameEmpty: "氏名を入力してください",
  errUsernameEmpty: "ユーザー名を選択してください",
  errUsernameTaken: "このユーザー名は既に使用されています",
  errEmailEmpty: "メールアドレスを入力してください",
  errPasswordEmpty: "パスワードを入力してください",
  errPasswordsDoNotMatch: "パスワードが一致しません",
  errCaptchaIncorrect: "セキュリティコードが正しくありません",
  welcomeTitle: "エリートへようこそ！",
};
