/**
 * Inspirational quotes bank for the Parent Dashboard.
 * 150+ quotes in various languages with Arabic translations where applicable.
 * 1. If Arabic: keep as is.
 * 2. If other: Quote + [Arabic Translation].
 * 3. Each entry must be a single line.
 */

export interface Quote {
    text: string;
    author: string;
}

export const INSPIRATIONAL_QUOTES: Quote[] = [
    // --- Arabic (Keep as is) ---
    { text: "اطلبوا العلم من المهد إلى اللحد", author: "حكمة مأثورة" },
    { text: "العلم في الصغر كالنقش على الحجر", author: "حكمة عربية" },
    { text: "من سلك طريقاً يلتمس فيه علماً، سهل الله له به طريقاً إلى الجنة", author: "الحديث الشريف" },
    { text: "العلم ليس ما يعرف، بل ما ينفع", author: "الإمام الشافعي" },
    { text: "العقل السليم في الجسم السليم", author: "حكمة قديمة" },
    { text: "من لم يذق مر التعلم ساعة، تجرع ذل الجهل طول حياته", author: "الإمام الشافعي" },
    { text: "النجاح هو رحلة وليس محطة وصول", author: "حكمة معاصرة" },
    { text: "الوقت كالسيف إن لم تقطعه قطعك", author: "حكمة عربية" },
    { text: "ما ضاع حق وراءه طالب", author: "مثل عربي" },
    { text: "تفاءلوا بالخير تجدوه", author: "حكمة مأثورة" },
    { text: "الخير في ما اختاره الله", author: "حكمة مأثورة" },
    { text: "الصبر مفتاح الفرج", author: "مثل عربي" },
    { text: "لا تؤجل عمل اليوم إلى الغد", author: "حكمة مشهورة" },
    { text: "من جد وجد ومن زرع حصد", author: "مثل عربي" },
    { text: "اليد الواحدة لا تصفق", author: "مثل عربي" },
    { text: "كل إناء بما فيه ينضح", author: "مثل عربي" },
    { text: "من سار على الدرب وصل", author: "حكمة" },
    { text: "الكلمة الطيبة صدقة", author: "الحديث الشريف" },
    { text: "حب لأخيك ما تحب لنفسك", author: "الحديث الشريف" },
    { text: "الوقاية خير من العلاج", author: "حكمة طبية" },
    { text: "لو كان العلم بالمنى، لكان كل الخلق علماء", author: "الشافعي" },
    { text: "من تعلم لغة قوم أمن مكرهم", author: "حكمة" },
    { text: "أعز مكان في الدنى سرج سابح، وخير جليس في الزمان كتاب", author: "المتنبي" },
    { text: "أنت اليوم حيث أوصلتك أفكارك، وستكون غداً حيث تأخذك أفكارك", author: "جيمس ألين" },
    { text: "القراءة غذاء الروح", author: "حكمة" },

    // --- French (+ Arabic Translation) ---
    { text: "Le savoir est la seule richesse que l'on peut emporter avec soi [العلم هو الثروة الوحيدة التي يمكن للمرء أن يأخذها معه]", author: "Proverbe" },
    { text: "Rien n'est impossible à celui qui essaie [لا شيء مستحيل لمن يحاول]", author: "Alexandre le Grand" },
    { text: "Petit à petit, l'oiseau fait son nid [خطوة بخطوة يبني الطائر عشه]", author: "Proverbe français" },
    { text: "Vouloir, c'est pouvoir [الإرادة هي القدرة]", author: "Proverbe" },
    { text: "La patience est amère, mais son fruit est doux [الصبر مر، ولكن ثمرته حلوة]", author: "Jean-Jacques Rousseau" },
    { text: "L'éducation est l'arme la plus puissante pour changer le monde [التعليم هو أقوى سلاح لتغيير العالم]", author: "Nelson Mandela" },
    { text: "Mieux vaut tard que jamais [أن تأتي متأخراً خير من ألا تأتي أبداً]", author: "Proverbe" },
    { text: "Tout vient à point à qui sait attendre [كل شيء يأتي في وقته لمن يعرف كيف ينتظر]", author: "Clément Marot" },
    { text: "Un sourire coûte moins cher que l'électricité, mais il donne autant de lumière [الابتسامة تكلف أقل من الكهرباء، لكنها تعطي نفس القدر من الضوء]", author: "Abbé Pierre" },
    { text: "On ne voit bien qu'avec le cœur [لا يرى المرء جيداً إلا بقلبه]", author: "Antoine de Saint-Exupéry" },
    { text: "Vivre, c'est apprendre [الحياة هي التعلم]", author: "Proverbe" },
    { text: "L'habit ne fait pas le moine [المظهر لا يعكس الجوهر دائماً]", author: "Proverbe" },
    { text: "L'union fait la force [في الاتحاد قوة]", author: "Proverbe" },
    { text: "Qui cherche, trouve [من يبحث يجد]", author: "Proverbe" },
    { text: "Il faut cultiver notre jardin [يجب أن نعتني بحديقتنا الخاصة]", author: "Voltaire" },
    { text: "La vie est un mystère qu'il faut vivre [الحياة لغز يجب عيشه]", author: "Gandhi" },
    { text: "Le temps est un grand maître [الوقت معلم عظيم]", author: "Corneille" },
    { text: "Chaque jour est une nouvelle chance [كل يوم هو فرصة جديدة]", author: "Anonyme" },
    { text: "Le courage n'est pas l'absence de peur [الشجاعة ليست غياب الخوف]", author: "Nelson Mandela" },
    { text: "Le génie est une longue patience [العبقرية هي صبر طويل]", author: "Buffon" },

    // --- English (+ Arabic Translation) ---
    { text: "The only limit to our realization of tomorrow will be our doubts of today [الحد الوحيد لتحقيقنا للغد سيكون شكوكنا اليوم]", author: "F.D. Roosevelt" },
    { text: "Believe you can and you're halfway there [آمن بأنك تستطيع وستكون قد قطعت نصف الطريق]", author: "Theodore Roosevelt" },
    { text: "Education is not preparation for life; education is life itself [التعليم ليس استعداداً للحياة؛ التعليم هو الحياة نفسها]", author: "John Dewey" },
    { text: "Success is not final, failure is not fatal [النجاح ليس نهائياً، والفشل ليس قاتلاً]", author: "Winston Churchill" },
    { text: "In the middle of difficulty lies opportunity [في منتصف الصعوبة تكمن الفرصة]", author: "Albert Einstein" },
    { text: "Don't count the days, make the days count [لا تعد الأيام، بل اجعل الأيام ذات قيمة]", author: "Muhammad Ali" },
    { text: "Your time is limited, don't waste it [وقتك محدود، فلا تضيعه]", author: "Steve Jobs" },
    { text: "Stay hungry, stay foolish [ابقَ جائعاً للمعرفة، ابقَ مغامراً]", author: "Steve Jobs" },
    { text: "It always seems impossible until it's done [يبدو الأمر مستحيلاً دائماً حتى يتم إنجازه]", author: "Nelson Mandela" },
    { text: "Dream big and dare to fail [احلم أحلاماً كبيرة وتجرأ على الفشل]", author: "Norman Vaughan" },
    { text: "The best way to predict the future is to create it [أفضل طريقة للتنبؤ بالمستقبل هي ابتكاره]", author: "Peter Drucker" },
    { text: "Excellence is not an act, but a habit [التميز ليس فعلاً، بل هو عادة]", author: "Aristotle" },
    { text: "Knowledge is power [المعرفة قوة]", author: "Francis Bacon" },
    { text: "Be the change that you wish to see in the world [كن أنت التغيير الذي تريد أن تراه في العالم]", author: "Gandhi" },
    { text: "Happiness depends upon ourselves [السعادة تعتمد على أنفسنا]", author: "Aristotle" },
    { text: "Imagination is more important than knowledge [الخيال أهم من المعرفة]", author: "Albert Einstein" },
    { text: "Turn your wounds into wisdom [حول جروحك إلى حكمة]", author: "Oprah Winfrey" },
    { text: "Action is the foundational key to all success [العمل هو المفتاح الأساسي لكل نجاح]", author: "Pablo Picasso" },
    { text: "Opportunities don't happen. You create them [الفرص لا تحدث من تلقاء نفسها، بل أنت من يخلقها]", author: "Chris Grosser" },
    { text: "If you want to lift yourself up, lift up someone else [إذا كنت تريد أن ترفع نفسك، فارفع شخصاً آخر]", author: "Booker T. Washington" },

    // --- Latin (+ Arabic Translation) ---
    { text: "Per aspera ad astra [عبر الصعاب إلى النجوم]", author: "Proverbium" },
    { text: "Scientia potentia est [المعرفة قوة]", author: "Francis Bacon" },
    { text: "Carpe diem [اغتنم اليوم]", author: "Horace" },
    { text: "Veni, vidi, vici [جئت، رأيت، انتصرت]", author: "Julius Caesar" },
    { text: "Mens sana in corpore sano [عقل سليم في جسم سليم]", author: "Juvenal" },
    { text: "Tempus fugit [الوقت يمر]", author: "Virgil" },
    { text: "Amor vincit omnia [الحب ينتصر على كل شيء]", author: "Virgil" },
    { text: "Nemo solus satis sapit [لا أحد حكيم بما يكفي بمفرده]", author: "Plautus" },
    { text: "Dum spiro spero [بينما أتنفس، آمل]", author: "Theocritus" },
    { text: "Ars longa, vita brevis [الفن طويل، والحياة قصيرة]", author: "Hippocrates" },
    { text: "Docendo discimus [نتعلم من خلال التعليم]", author: "Seneca" },
    { text: "In hoc signo vinces [بهذه العلامة ستنتصر]", author: "Constantine" },
    { text: "Post meridian [بعد الظهر]", author: "Common" },
    { text: "Labor omnia vincit [العمل يتغلب على كل شيء]", author: "Virgil" },
    { text: "Non scholae sed vitae discimus [لا نتعلم من أجل المدرسة بل من أجل الحياة]", author: "Seneca" },
    { text: "Aut inveniam viam aut faciam [إما سأجد طريقاً أو سأصنعه]", author: "Hannibal" },
    { text: "Festina lente [أسرع ببطء]", author: "Augustus" },
    { text: "Sapere aude [تجرأ على المعرفة]", author: "Horace" },
    { text: "Virtus junxit mors non separabit [ما جمعه الوفاء لن يفرقه الموت]", author: "Common" },
    { text: "Memento vivere [تذكر أن تعيش]", author: "Ancient wisdom" },

    // --- Spanish (+ Arabic Translation) ---
    { text: "El que lee mucho y anda mucho, ve mucho y sabe mucho [من يقرأ كثيراً ويمشي كثيراً، يرى كثيراً ويعرف كثيراً]", author: "Miguel de Cervantes" },
    { text: "La vida es corta, pero una sonrisa solo toma un segundo [الحياة قصيرة، لكن الابتسامة لا تستغرق سوى ثانية]", author: "Anónimo" },
    { text: "Haz el bien sin mirar a quién [افعل الخير دون النظر إلى من سيتلقاه]", author: "Dicho popular" },
    { text: "A falta de pan, buenas son tortas [عند فقدان الخبز، الكعك جيد أيضاً]", author: "Refrán" },
    { text: "Más vale pájaro en mano que cien volando [عصفور في اليد خير من عشرة على الشجرة]", author: "Refrán" },
    { text: "No hay mal que por bien no venga [لا يوجد شر لا يأتي منه خير]", author: "Refrán" },
    { text: "Siembra un pensamiento, cosecha una acción [ازرع فكراً، تحصد فعلاً]", author: "Anónimo" },
    { text: "El saber no ocupa lugar [المعرفة لا تأخذ حيزاً]", author: "Dicho" },
    { text: "Querer es poder [الإرادة هي القدرة]", author: "Dicho" },
    { text: "Vivir es increíble [الحياة مذهلة]", author: "Anónimo" },
    { text: "Todo esfuerzo tiene su recompensa [كل جهد له مكافأته]", author: "Proverbio" },
    { text: "La unión hace la fuerza [في الاتحاد قوة]", author: "Eslogan" },
    { text: "Hoy es el primer día del resto de tu vida [اليوم هو أول يوم في بقية حياتك]", author: "Dicho" },
    { text: "Cada día es un regalo [كل يوم هو هدية]", author: "Anónimo" },
    { text: "Sé tú mismo [كن نفسك]", author: "Consejo" },
    { text: "La felicidad nace de adentro [السعادة تنبع من الداخل]", author: "Proverbio" },
    { text: "Nunca es tarde para aprender [لم يفت الأوان بعد للتعلم]", author: "Dicho" },
    { text: "Ríe y el mundo reirá contigo [اضحك وسوف يضحك العالم معك]", author: "Ella Wheeler Wilcox" },
    { text: "La esperanza es lo último que se pierde [الأمل هو آخر ما تفقده]", author: "Dicho" },
    { text: "El sol sale para todos [الشمس تشرق للجميع]", author: "Refrán" },

    // --- Italian (+ Arabic Translation) ---
    { text: "La vita è bella [الحياة جميلة]", author: "Roberto Benigni" },
    { text: "Chi dorme non piglia pesci [من ينم لا يصطاد السمك]", author: "Proverbio" },
    { text: "A goccia a goccia si scava la pietra [قطرة تلو قطرة تحفر الحجر]", author: "Anselmo d'Aosta" },
    { text: "Chi va piano va sano e va lontano [من يسير ببطء يسير بأمان ويذهب بعيداً]", author: "Proverbio" },
    { text: "L'amore è cieco [الحب أعمى]", author: "Proverbio" },
    { text: "Meglio tardi che mai [أن تأتي متأخراً خير من ألا تأتي أبداً]", author: "Proverbio" },
    { text: "Finché c'è vita c'è speranza [طالما هناك حياة، هناك أمل]", author: "Proverbio" },
    { text: "Ogni cosa a suo tempo [كل شيء في وقته المكتوب]", author: "Proverbio" },
    { text: "L'unione fa la forza [في الاتحاد قوة]", author: "Motto" },
    { text: "La pazienza è la virtù dei forti [الصبر هو فضيلة الأقوياء]", author: "Proverbio" },
    { text: "Ognuno è artefice del proprio destino [كل شخص هو صانع قدره]", author: "Appio Claudio Cieco" },
    { text: "Il tempo vola [الوقت يطير]", author: "Virgilio" },
    { text: "Vivi e lascia vivere [عش ودع غيرك يعيش]", author: "Motto" },
    { text: "Sbagliando s'impara [من خلال الوقوع في الأخطاء، نتعلم]", author: "Proverbio" },
    { text: "La verità ti renderà libero [الحقيقة سوف تحررك]", author: "Bibbia" },
    { text: "Tutto è possibile [كل شيء ممكن]", author: "Anid" },
    { text: "Cogli l'attimo [اغتنم اللحظة]", author: "Orazio" },
    { text: "La sapienza è figlia dell'esperienza [الحكمة هي ابنة التجربة]", author: "Leonardo da Vinci" },
    { text: "Senza fretta ma senza sosta [بلا تسرع ولكن دون توقف]", author: "Goethe" },
    { text: "Il mattino ha l'oro in bocca [الصباح في فمه ذهب - دلالة على البركة في التبكير]", author: "Proverbio" },

    // --- German (+ Arabic Translation) ---
    { text: "Übung macht den Meister [التدريب يصنع الأبطال]", author: "Sprichwort" },
    { text: "Wissen ist Macht [المعرفة قوة]", author: "Francis Bacon" },
    { text: "Morgenstund hat Gold im Mund [البركة في التبكير]", author: "Sprichwort" },
    { text: "Geduld bringt Rosen [الصبر يأتي بالورود]", author: "Christoph Martin Wieland" },
    { text: "Wer A sagt, muss auch B sagen [من يقل ألف، عليه أن يكمل الباء]", author: "Bertolt Brecht" },
    { text: "Aller Anfang ist schwer [كل بداية صعبة]", author: "Sprichwort" },
    { text: "Denken ist schwer, darum urteilen die meisten [التفكير صعب، لذا يفضل معظم الناس إطلاق الأحكام]", author: "Carl Jung" },
    { text: "Das Leben ist kein Wunschkonzert [الحياة ليست حفلة أماني]", author: "Sprichwort" },
    { text: "In der Ruhe liegt die Kraft [في الهدوء تكمن القوة]", author: "Sprichwort" },
    { text: "Lernen ist wie Rudern gegen den Strom [التعلم مثل التجديف ضد التيار]", author: "Laozi" },
    { text: "Mut steht am Anfang des Handelns, Glück am Ende [الشجاعة في بداية العمل، والحظ في نهايته]", author: "Demokrit" },
    { text: "Man muss das Unmögliche versuchen, um das Mögliche zu erreichen [يجب محاولة المستحيل لتحقيق الممكن]", author: "Hermann Hesse" },
    { text: "Der Weg ist das Ziel [الطريق هو الهدف]", author: "Konfuzius" },
    { text: "Jeder Tag ist ein neuer Anfang [كل يوم هو بداية جديدة]", author: "Goethe" },
    { text: "Stille Wasser sind tief [المياه الهادئة عميقة]", author: "Sprichwort" },
    { text: "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren [من يقاتل قد يخسر، لكن من لا يقاتل فاز بالخسارة حتماً]", author: "Bertolt Brecht" },
    { text: "Bücher sind fliegende Teppiche ins Reich der Phantasie [الكتب هي سجاد طائر إلى مملكة الخيال]", author: "James Daniel" },
    { text: "Das Beste kommt noch [الأفضل يلم يأتِ بعد]", author: "Sprichwort" },
    { text: "Ohne Fleiß kein Preis [لا جائزة بلا اتقان وعمل]", author: "Sprichwort" },
    { text: "Genieße den Augenblick [استمتع باللحظة الحالية]", author: "Sprichwort" },

    // --- More Arabic Deep Wisdom (Algerian/North African focus where possible) ---
    { text: "ما يجي الشهد غير من عند النحل [لا يأتي العسل إلا من عند النحل]", author: "مثل شعبي" },
    { text: "اضحك للدنيا تضحكلك", author: "حكمة شائعة" },
    { text: "الصحبة الصافية والنية الصادقة", author: "مقولة مأثورة" },
    { text: "اخدم صغري لكبري", author: "مثل جزائري" },
    { text: "الحضرة بالايدين والضحكة بالعينين", author: "مثل شعبي" },
    { text: "من بغى الربح، يدخل في الساحة", author: "مثل جزائري" },
    { text: "اللي قرأ قرأ بكري", author: "مثل شعبي" },
    { text: "كل خنفوس عند يماه غزال", author: "مثل جزائري" },
    { text: "يد الله مع الجماعة", author: "حكمة إسلامية" },
    { text: "النية تغلب القبيح", author: "مثل شعبي" },
    { text: "من تواضع لله رفعه", author: "حكمة إسلامية" },
    { text: "العلم نور والجهل ظلام", author: "مثل معروف" },
    { text: "عاند ولا تحسد", author: "مثل شعبي" },
    { text: "السكوت حكمة", author: "مثل عربي" },
    { text: "الجار قبل الدار", author: "وصية عربية" },
    { text: "كلام الليل يمحوه النهار", author: "مثل عربي" },
    { text: "الحاجة أم الاختراع", author: "حكمة عالمية" },
    { text: "اللسان الحلو يرضع اللبؤة", author: "حكمة جزائرية" },
    { text: "اللي فات مات", author: "مثل شعبي" },
    { text: "الشمس تطلع على الجميع", author: "حكمة" },
    { text: "الصبر كنز من كنوز الجنة", author: "حكمة" },
    { text: "البركة في القليل", author: "مثل شعبي" },
    { text: "خير الكلام ما قل ودل", author: "مثل عربي" },
    { text: "ما يبقى في الواد غير حجارو", author: "مثل جزائري مأثور" },
    { text: "العلم صيد والكتابة قيده", author: "حكمة" },
    { text: "من عرف لغتين، عاش حياتين", author: "حكمة" },

    // --- Japanese (Romaji + Translation) ---
    { text: "Nana korobi ya oki [سقط سبع مرات، ونهض ثمانية]", author: "Proverb" },
    { text: "Ichi-go ichi-e [لحظة واحدة، فرصة واحدة]", author: "Tea ceremony wisdom" },
    { text: "Keizoku wa chikara nari [الاستمرارية هي القوة]", author: "Proverb" },
    { text: "Sarumo ki kara ochiru [حتى القرود تسقط من الأشجار - دليل على أن الكل يخطئ]", author: "Proverb" },
    { text: "Chiri mo tsumoreba yama to naru [حتى الغبار، عندما يتراكم، يصبح جبلاً]", author: "Proverb" },

    // --- Final additions to reach 150+ ---
    { text: "Persistence is the path to victory [الإصرار هو طريق النصر]", author: "Anonymous" },
    { text: "Courage is being afraid but going on anyway [الشجاعة هي أن تكون خائفاً ولكن تستمر على أي حال]", author: "Dan Rather" },
    { text: "Education is the key to unlock the golden door of freedom [التعليم هو المفتاح لفتح الباب الذهبي للحرية]", author: "George Washington Carver" },
    { text: "Believe in yourself [آمن بنفسك]", author: "Advice" },
    { text: "Do it with passion or not at all [افعله بشغف أو لا تفعله على الإطلاق]", author: "Motto" },
    { text: "Your hard work will pay off [عملك الشاق سيؤتي ثماره]", author: "Encouragement" },
    { text: "Focus is the key [التركيز هو المفتاح]", author: "Wisdom" },
    { text: "Never give up on your dreams [لا تتخلَ أبداً عن أحلامك]", author: "Common sense" },
    { text: "Strive for progress, not perfection [اسعَ للتقدم وليس للمثالية]", author: "Motto" },
    { text: "Consistency is key [الاستمرارية هي السر]", author: "Proverb" },
    { text: "Stay positive [ابقَ إيجابياً]", author: "Advice" },
    { text: "Make it happen [اجعل الأمر حقيقة]", author: "Call to action" },
    { text: "Learn something new every day [تعلم شيئاً جديداً كل يوم]", author: "Goal" },
    { text: "Wisdom begins in wonder [الحكمة تبدأ بالدهشة]", author: "Socrates" },
    { text: "Knowledge speaks, but wisdom listens [المعرفة تتحدث، لكن الحكمة تستمع]", author: "Jimi Hendrix" },
    { text: "Be brave [كن شجاعاً]", author: "Command" },
    { text: "Find joy in the journey [ابحث عن الفرح في الرحلة]", author: "Wisdom" },
    { text: "Create your own sunshine [اصنع شروقك الخاص]", author: "Advice" },
    { text: "Small steps lead to big changes [الخطوات الصغيرة تؤدي إلى تغييرات كبيرة]", author: "Proverb" },
    { text: "The future belongs to the curious [المستقبل ينتمي إلى الفضوليين]", author: "Anonymous" }
];
